#include "Opcodes.hpp"

void def(CPU::Z80 *)
{
  return;
}

t_op opcodes[] = {
    {"NOP", 0x00, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x00)},
    {"LD BC, d16", 0x01, 3, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x01)},
    {"LD (BC), A", 0x02, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x02)},
    {"INC BC", 0x03, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x03)},
    {"INC B", 0x04, 1, 4, {INST_SET, CLEAR, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x04)},
    {"DEC B", 0x05, 1, 4, {INST_SET, SET, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x05)},
    {"LD B, d8", 0x06, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x06)},
    {"RLCA", 0x07, 1, 4, {CLEAR, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::Dis0x07)},
    {"LD (a16), SP", 0x08, 3, 20, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x08)},
    {"ADD HL, BC", 0x09, 1, 8, {UNCHANGED, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x09)},
    {"LD A, (BC)", 0x0A, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x0A)},
    {"DEC BC", 0x0B, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x0B)},
    {"INC C", 0x0C, 1, 4, {INST_SET, CLEAR, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x0C)},
    {"DEC C", 0x0D, 1, 4, {INST_SET, SET, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x0D)},
    {"LD C, d8", 0x0E, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x0E)},
    {"RRCA", 0x0F, 1, 4, {CLEAR, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::Dis0x0F)},

    {"STOP 0", 0x10, 2, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x10)},
    {"LD DE, d16", 0x11, 3, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x11)},
    {"LD (DE), A", 0x12, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x12)},
    {"INC DE", 0x13, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x13)},
    {"INC D", 0x14, 1, 4, {INST_SET, CLEAR, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x14)},
    {"DEC D", 0x15, 1, 4, {INST_SET, SET, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x15)},
    {"LD D, d8", 0x16, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x16)},
    {"RLA", 0x17, 1, 4, {CLEAR, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::Dis0x17)},
    {"JR r8", 0x18, 2, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x18)},
    {"ADD HL, DE", 0x19, 1, 8, {UNCHANGED, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x19)},
    {"LD A, (DE)", 0x1A, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x1A)},
    {"DEC DE", 0x1B, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x1B)},
    {"INC E", 0x1C, 1, 4, {INST_SET, CLEAR, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x1C)},
    {"DEC E", 0x1D, 1, 4, {INST_SET, SET, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x1D)},
    {"LD E, d8", 0x1E, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x1E)},
    {"RRA", 0x1F, 1, 4, {CLEAR, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::Dis0x1F)},

    {"JR NZ, r8", 0x20, 2, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x20)},
    {"LD HL, d16", 0x21, 3, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x21)},
    {"LD (HL+), A", 0x22, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x22)},
    {"INC HL", 0x23, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x23)},
    {"INC H", 0x24, 1, 4, {INST_SET, CLEAR, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x24)},
    {"DEC H", 0x25, 1, 4, {INST_SET, SET, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x25)},
    {"LD H, d8", 0x26, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x26)},
    {"DAA", 0x27, 1, 4, {INST_SET, UNCHANGED, CLEAR, INST_SET}, &(CPU::Disasm::Dis0x27)},
    {"JR Z, r8", 0x28, 2, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x28)},
    {"ADD HL, HL", 0x29, 1, 8, {UNCHANGED, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x29)},
    {"LD A, (HL+)", 0x2A, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x2A)},
    {"DEC HL", 0x2B, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x2B)},
    {"INC L", 0x2C, 1, 4, {INST_SET, CLEAR, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x2C)},
    {"DEC L", 0x2D, 1, 4, {INST_SET, SET, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x2D)},
    {"LD L, d8", 0x2E, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x2E)},
    {"CPL", 0x2F, 1, 4, {UNCHANGED, SET, SET, UNCHANGED}, &(CPU::Disasm::Dis0x2F)},

    {"JR NC, r8", 0x30, 2, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x30)},
    {"LD SP, d16", 0x31, 3, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x31)},
    {"LD (HL-), A", 0x32, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x32)},
    {"INC SP", 0x33, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x33)},
    {"INC (HL)", 0x34, 1, 12, {INST_SET, CLEAR, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x34)},
    {"DEC (HL)", 0x35, 1, 12, {INST_SET, SET, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x35)},
    {"LD (HL), d8", 0x36, 2, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x36)},
    {"SCF", 0x37, 1, 4, {UNCHANGED, CLEAR, CLEAR, SET}, &(CPU::Disasm::Dis0x37)},
    {"JR C, r8", 0x38, 2, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x38)},
    {"ADD HL, SP", 0x39, 1, 8, {UNCHANGED, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x39)},
    {"LD A, (HL-)", 0x3A, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x3A)},
    {"DEC SP", 0x3B, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x3B)},
    {"INC A", 0x3C, 1, 4, {INST_SET, CLEAR, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x3C)},
    {"DEC A", 0x3D, 1, 4, {INST_SET, SET, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x3D)},
    {"LD A, d8", 0x3E, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x3E)},
    {"CCF", 0x3F, 1, 4, {UNCHANGED, SET, SET, UNCHANGED}, &(CPU::Disasm::Dis0x3F)},

    {"LD B, B", 0x40, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x40)},
    {"LD B, C", 0x41, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x41)},
    {"LD B, D", 0x42, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x42)},
    {"LD B, E", 0x43, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x43)},
    {"LD B, H", 0x44, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x44)},
    {"LD B, L", 0x45, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x45)},
    {"LD B, (HL)", 0x46, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x46)},
    {"LD B, A", 0x47, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x47)},
    {"LD C, B", 0x48, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x48)},
    {"LD C, C", 0x49, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x49)},
    {"LD C, D", 0x4A, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x4A)},
    {"LD C, E", 0x4B, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x4B)},
    {"LD C, H", 0x4C, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x4C)},
    {"LD C, L", 0x4D, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x4D)},
    {"LD C, (HL)", 0x4E, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x4E)},
    {"LD C, A", 0x4F, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x4F)},

    {"LD D, B", 0x50, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x50)},
    {"LD D, C", 0x51, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x51)},
    {"LD D, D", 0x52, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x52)},
    {"LD D, E", 0x53, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x53)},
    {"LD D, H", 0x54, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x54)},
    {"LD D, L", 0x55, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x55)},
    {"LD D, (HL)", 0x56, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x56)},
    {"LD D, A", 0x57, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x57)},
    {"LD E, B", 0x58, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x58)},
    {"LD E, C", 0x59, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x59)},
    {"LD E, D", 0x5A, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x5A)},
    {"LD E, E", 0x5B, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x5B)},
    {"LD E, H", 0x5C, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x5C)},
    {"LD E, L", 0x5D, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x5D)},
    {"LD E, (HL)", 0x5E, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x5E)},
    {"LD E, A", 0x5F, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x5F)},

    {"LD H, B", 0x60, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x60)},
    {"LD H, C", 0x61, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x61)},
    {"LD H, D", 0x62, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x62)},
    {"LD H, E", 0x63, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x63)},
    {"LD H, H", 0x64, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x64)},
    {"LD H, L", 0x65, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x65)},
    {"LD H, (HL)", 0x66, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x66)},
    {"LD H, A", 0x67, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x67)},
    {"LD L, B", 0x68, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x68)},
    {"LD L, C", 0x69, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x69)},
    {"LD L, D", 0x6A, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x6A)},
    {"LD L, E", 0x6B, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x6B)},
    {"LD L, H", 0x6C, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x6C)},
    {"LD L, L", 0x6D, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x6D)},
    {"LD L, (HL)", 0x6E, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x6E)},
    {"LD L, A", 0x6F, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x6F)},

    {"LD (HL), B", 0x70, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x70)},
    {"LD (HL), C", 0x71, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x71)},
    {"LD (HL), D", 0x72, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x72)},
    {"LD (HL), E", 0x73, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x73)},
    {"LD (HL), H", 0x74, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x74)},
    {"LD (HL), L", 0x75, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x75)},
    {"LD (HL), (HL)", 0x76, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x76)},
    {"LD (HL), A", 0x77, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x77)},
    {"LD A, B", 0x78, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x78)},
    {"LD A, C", 0x79, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x79)},
    {"LD A, D", 0x7A, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x7A)},
    {"LD A, E", 0x7B, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x7B)},
    {"LD A, H", 0x7C, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x7C)},
    {"LD A, L", 0x7D, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x7D)},
    {"LD A, (HL)", 0x7E, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x7E)},
    {"LD A, A", 0x7F, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x7F)},

    {"ADD A, B", 0x80, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x80)},
    {"ADD A, C", 0x81, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x81)},
    {"ADD A, D", 0x82, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x82)},
    {"ADD A, E", 0x83, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x83)},
    {"ADD A, H", 0x84, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x84)},
    {"ADD A, L", 0x85, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x85)},
    {"ADD A, (HL)", 0x86, 1, 8, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x86)},
    {"ADD A, A", 0x87, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x87)},
    {"ADC A, B", 0x88, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x88)},
    {"ADC A, C", 0x89, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x89)},
    {"ADC A, D", 0x8A, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x8A)},
    {"ADC A, E", 0x8B, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x8B)},
    {"ADC A, H", 0x8C, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x8C)},
    {"ADC A, L", 0x8D, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x8D)},
    {"ADC A, (HL)", 0x8E, 1, 8, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x8E)},
    {"ADC A, A", 0x8F, 1, 4, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x8F)},

    {"SUB A, B", 0x90, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x90)},
    {"SUB A, C", 0x91, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x91)},
    {"SUB A, D", 0x92, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x92)},
    {"SUB A, E", 0x93, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x93)},
    {"SUB A, H", 0x94, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x94)},
    {"SUB A, L", 0x95, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x95)},
    {"SUB A, (HL)", 0x96, 1, 8, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x96)},
    {"SUB A, A", 0x97, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x97)},
    {"SBC A, B", 0x98, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x98)},
    {"SBC A, C", 0x99, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x99)},
    {"SBC A, D", 0x9A, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x9A)},
    {"SBC A, E", 0x9B, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x9B)},
    {"SBC A, H", 0x9C, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x9C)},
    {"SBC A, L", 0x9D, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x9D)},
    {"SBC A, (HL)", 0x9E, 1, 8, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x9E)},
    {"SBC A, A", 0x9F, 1, 4, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x9F)},

    {"AND B", 0xA0, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xA0)},
    {"AND C", 0xA1, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xA1)},
    {"AND D", 0xA2, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xA2)},
    {"AND E", 0xA3, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xA3)},
    {"AND H", 0xA4, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xA4)},
    {"AND L", 0xA5, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xA5)},
    {"AND (HL)", 0xA6, 1, 8, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xA6)},
    {"AND A", 0xA7, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xA7)},
    {"XOR B", 0xA8, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xA8)},
    {"XOR C", 0xA9, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xA9)},
    {"XOR D", 0xAA, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xAA)},
    {"XOR E", 0xAB, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xAB)},
    {"XOR H", 0xAC, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xAC)},
    {"XOR L", 0xAD, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xAD)},
    {"XOR (HL)", 0xAE, 1, 8, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xAE)},
    {"XOR A", 0xAF, 1, 4, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xAF)},

    {"OR B", 0xB0, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xB0)},
    {"OR C", 0xB1, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xB1)},
    {"OR D", 0xB2, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xB2)},
    {"OR E", 0xB3, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xB3)},
    {"OR H", 0xB4, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xB4)},
    {"OR L", 0xB5, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xB5)},
    {"OR (HL)", 0xB6, 1, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xB6)},
    {"OR A", 0xB7, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xB7)},
    {"CP B", 0xB8, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xB8)},
    {"CP C", 0xB9, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xB9)},
    {"CP D", 0xBA, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xBA)},
    {"CP E", 0xBB, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xBB)},
    {"CP H", 0xBC, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xBC)},
    {"CP L", 0xBD, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xBD)},
    {"CP (HL)", 0xBE, 1, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xBE)},
    {"CP A", 0xBF, 1, 4, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xBF)},

    {"RET NZ", 0xC0, 1, 20, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xC0)},
    {"POP BC", 0xC1, 1, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xC1)},
    {"JP NZ, a16", 0xC2, 3, 22, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xC2)},
    {"JP a16", 0xC3, 3, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xC3)},
    {"CALL NZ, a16", 0xC4, 3, 24, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xC4)},
    {"PUSH BC", 0xC5, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xC5)},
    {"ADD A, d8", 0xC6, 2, 8, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0xC6)},
    {"RST 00", 0xC7, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xC7)},
    {"RET Z", 0xC8, 1, 20, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xC8)},
    {"RET", 0xC9, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xC9)},
    {"JP Z, a16", 0xCA, 3, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xCA)},
    {"PREFIX CB", 0xCB, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xCB)},
    {"CALL Z, a16", 0xCC, 3, 24, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xCC)},
    {"CALL a16", 0xCD, 3, 24, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xCD)},
    {"ADC A, d8", 0xCE, 2, 8, {INST_SET, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0xCE)},
    {"RST 08", 0xCF, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xCF)},

    {"RET NC", 0xD0, 1, 20, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xD0)},
    {"POP DE", 0xD1, 1, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xD1)},
    {"JP NC, a16", 0xD2, 3, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xD2)},
    // 0xD3 : Instruction does not exist.
    {"CALL NC, a16", 0xD4, 3, 24, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xD4)},
    {"PUSH DE", 0xD5, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xD5)},
    {"SUB d8", 0xD6, 2, 8, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0xD6)},
    {"RST 10H", 0xD7, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xD7)},
    {"RET C", 0xD8, 1, 20, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xD8)},
    {"RETI", 0xD9, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xD9)},
    {"JP C, a16", 0xDA, 3, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xDA)},
    // 0xDB : Instruction does not exist.
    {"CALL C, a16", 0xDC, 3, 24, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xDC)},
    // 0xDD : Instruction does not exist.
    {"SBC A, d8", 0xDE, 2, 8, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0xDE)},
    {"RST 18", 0xDF, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xDF)},

    {"LDH (a8), A", 0xE0, 2, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xE0)},
    {"POP HL", 0xE1, 1, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xE1)},
    {"LD (C), A", 0xE2, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xE2)},
    // 0xE3 : Instruction does not exist.
    // 0xE4 : Instruction does not exist.
    {"PUSH HL", 0xE5, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xE5)},
    {"AND d8", 0xE6, 2, 8, {INST_SET, CLEAR, SET, CLEAR}, &(CPU::Disasm::Dis0xE6)},
    {"RST 20", 0xE7, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xE7)},
    {"ADD SP, r8", 0xE8, 2, 16, {CLEAR, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0xE8)},
    {"JP (HL)", 0xE9, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xE9)},
    {"LD (a16), A", 0xEA, 3, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xEA)},
    // 0xEB : Instruction does not exist.
    // 0xEC : Instruction does not exist.
    // 0xED : Instruction does not exist.
    {"XOR d8", 0xEE, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xEE)},
    {"RST 28", 0xEF, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xEF)},

    {"LD A, (a8)", 0xF0, 2, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xF0)},
    {"POP AF", 0xF1, 1, 12, {INST_SET, INST_SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0xF1)},
    {"LD A, (C)", 0xF2, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xF2)},
    {"DI", 0xF3, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xF3)},
    // 0xF4 : Instruction does not exist.
    {"PUSH AF", 0xF5, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xF5)},
    {"OR d8", 0xF6, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::Dis0xF6)},
    {"RST 30", 0xF7, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xF7)},
    {"LD HL, SP + r8", 0xF8, 2, 12, {CLEAR, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0xF8)},
    {"LD SP, HL", 0xF9, 1, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xF9)},
    {"LD A, (a16)", 0xFA, 3, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xFA)},
    {"EI", 0xFB, 1, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xFB)},
    // 0xFC : Instruction does not exist.
    // 0xFD : Instruction does not exist.
    {"CP d8", 0xFE, 2, 8, {INST_SET, SET, INST_SET, INST_SET}, &(CPU::Disasm::Dis0xFE)},
    {"RST 38", 0xFF, 1, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0xFF)},

    {{0}, 0, 0, 0, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &def}};

t_op ext_opcodes[] = {

    {"RLC B", 0x00, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x00)},
    {"RLC C", 0x01, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x01)},
    {"RLC D", 0x02, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x02)},
    {"RLC E", 0x03, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x03)},
    {"RLC H", 0x04, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x04)},
    {"RLC L", 0x05, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x05)},
    {"RLC (HL)", 0x06, 2, 16, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x06)},
    {"RLC A", 0x07, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x07)},
    {"RRC B", 0x08, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x08)},
    {"RRC C", 0x09, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x09)},
    {"RRC D", 0x0A, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x0A)},
    {"RRC E", 0x0B, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x0B)},
    {"RRC H", 0x0C, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x0C)},
    {"RRC L", 0x0D, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x0D)},
    {"RRC (HL)", 0x0E, 2, 16, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x0E)},
    {"RRC A", 0x0F, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x0F)},

    {"RL B", 0x10, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x10)},
    {"RL C", 0x11, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x11)},
    {"RL D", 0x12, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x12)},
    {"RL E", 0x13, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x13)},
    {"RL H", 0x14, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x14)},
    {"RL L", 0x15, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x15)},
    {"RL (HL)", 0x16, 2, 16, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x16)},
    {"RL A", 0x17, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x17)},
    {"RR B", 0x18, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x18)},
    {"RR C", 0x19, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x19)},
    {"RR D", 0x1A, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x1A)},
    {"RR E", 0x1B, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x1B)},
    {"RR H", 0x1C, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x1C)},
    {"RR L", 0x1D, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x1D)},
    {"RR (HL)", 0x1E, 2, 16, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x1E)},
    {"RR A", 0x1F, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x1F)},

    {"SLA B", 0x20, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x20)},
    {"SLA C", 0x21, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x21)},
    {"SLA D", 0x22, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x22)},
    {"SLA E", 0x23, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x23)},
    {"SLA H", 0x24, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x24)},
    {"SLA L", 0x25, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x25)},
    {"SLA (HL)", 0x26, 2, 16, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x26)},
    {"SLA A", 0x27, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x27)},
    {"SRA B", 0x28, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x28)},
    {"SRA C", 0x29, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x29)},
    {"SRA D", 0x2A, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x2A)},
    {"SRA E", 0x2B, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x2B)},
    {"SRA H", 0x2C, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x2C)},
    {"SRA L", 0x2D, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x2D)},
    {"SRA (HL)", 0x2E, 2, 16, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x2E)},
    {"SRA A", 0x2F, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x2F)},

    {"SWAP B", 0x30, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x30)},
    {"SWAP C", 0x31, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x31)},
    {"SWAP D", 0x32, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x32)},
    {"SWAP E", 0x33, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x33)},
    {"SWAP H", 0x34, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x34)},
    {"SWAP L", 0x35, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x35)},
    {"SWAP (HL)", 0x36, 2, 16, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x36)},
    {"SWAP A", 0x37, 2, 8, {INST_SET, CLEAR, CLEAR, CLEAR}, &(CPU::Disasm::DisCB0x37)},
    {"SRL B", 0x38, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x38)},
    {"SRL C", 0x39, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x39)},
    {"SRL D", 0x3A, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x3A)},
    {"SRL E", 0x3B, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x3B)},
    {"SRL H", 0x3C, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x3C)},
    {"SRL L", 0x3D, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x3D)},
    {"SRL (HL)", 0x3E, 2, 16, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x3E)},
    {"SRL A", 0x3F, 2, 8, {INST_SET, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::DisCB0x3F)},

    {"BIT 0, B", 0x40, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x40)},
    {"BIT 0, C", 0x41, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x41)},
    {"BIT 0, D", 0x42, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x42)},
    {"BIT 0, E", 0x43, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x43)},
    {"BIT 0, H", 0x44, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x44)},
    {"BIT 0, L", 0x45, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x45)},
    {"BIT 0, (HL)", 0x46, 2, 16, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x46)},
    {"BIT 0, A", 0x47, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x47)},
    {"BIT 1, B", 0x48, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x48)},
    {"BIT 1, C", 0x49, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x49)},
    {"BIT 1, D", 0x4A, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x4A)},
    {"BIT 1, E", 0x4B, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x4B)},
    {"BIT 1, H", 0x4C, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x4C)},
    {"BIT 1, L", 0x4D, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x4D)},
    {"BIT 1, (HL)", 0x4E, 2, 16, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x4E)},
    {"BIT 1, A", 0x4F, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x4F)},

    {"BIT 2, B", 0x50, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x50)},
    {"BIT 2, C", 0x51, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x51)},
    {"BIT 2, D", 0x52, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x52)},
    {"BIT 2, E", 0x53, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x53)},
    {"BIT 2, H", 0x54, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x54)},
    {"BIT 2, L", 0x55, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x55)},
    {"BIT 2, (HL)", 0x56, 2, 16, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x56)},
    {"BIT 2, A", 0x57, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x57)},
    {"BIT 3, B", 0x58, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x58)},
    {"BIT 3, C", 0x59, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x59)},
    {"BIT 3, D", 0x5A, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x5A)},
    {"BIT 3, E", 0x5B, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x5B)},
    {"BIT 3, H", 0x5C, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x5C)},
    {"BIT 3, L", 0x5D, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x5D)},
    {"BIT 3, (HL)", 0x5E, 2, 16, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x5E)},
    {"BIT 3, A", 0x5F, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x5F)},

    {"BIT 4, B", 0x60, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x60)},
    {"BIT 4, C", 0x61, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x61)},
    {"BIT 4, D", 0x62, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x62)},
    {"BIT 4, E", 0x63, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x63)},
    {"BIT 4, H", 0x64, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x64)},
    {"BIT 4, L", 0x65, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x65)},
    {"BIT 4, (HL)", 0x66, 2, 16, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x66)},
    {"BIT 4, A", 0x67, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x67)},
    {"BIT 5, B", 0x68, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x68)},
    {"BIT 5, C", 0x69, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x69)},
    {"BIT 5, D", 0x6A, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x6A)},
    {"BIT 5, E", 0x6B, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x6B)},
    {"BIT 5, H", 0x6C, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x6C)},
    {"BIT 5, L", 0x6D, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x6D)},
    {"BIT 5, (HL)", 0x6E, 2, 16, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x6E)},
    {"BIT 5, A", 0x6F, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x6F)},

    {"BIT 6, B", 0x70, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x70)},
    {"BIT 6, C", 0x71, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x71)},
    {"BIT 6, D", 0x72, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x72)},
    {"BIT 6, E", 0x73, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x73)},
    {"BIT 6, H", 0x74, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x74)},
    {"BIT 6, L", 0x75, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x75)},
    {"BIT 6, (HL)", 0x76, 2, 16, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x76)},
    {"BIT 6, A", 0x77, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x77)},
    {"BIT 7, B", 0x78, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x78)},
    {"BIT 7, C", 0x79, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x79)},
    {"BIT 7, D", 0x7A, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x7A)},
    {"BIT 7, E", 0x7B, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x7B)},
    {"BIT 7, H", 0x7C, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x7C)},
    {"BIT 7, L", 0x7D, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x7D)},
    {"BIT 7, (HL)", 0x7E, 2, 16, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x7E)},
    {"BIT 7, A", 0x7F, 2, 8, {INST_SET, CLEAR, SET, UNCHANGED}, &(CPU::Disasm::DisCB0x7F)},

    {"RES 0, B", 0x80, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x80)},
    {"RES 0, C", 0x81, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x81)},
    {"RES 0, D", 0x82, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x82)},
    {"RES 0, E", 0x83, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x83)},
    {"RES 0, H", 0x84, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x84)},
    {"RES 0, L", 0x85, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x85)},
    {"RES 0, (HL)", 0x86, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x86)},
    {"RES 0, A", 0x87, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x87)},
    {"RES 1, B", 0x88, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x88)},
    {"RES 1, C", 0x89, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x89)},
    {"RES 1, D", 0x8A, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x8A)},
    {"RES 1, E", 0x8B, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x8B)},
    {"RES 1, H", 0x8C, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x8C)},
    {"RES 1, L", 0x8D, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x8D)},
    {"RES 1, (HL)", 0x8E, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x8E)},
    {"RES 1, A", 0x8F, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x8F)},

    {"RES 2, B", 0x90, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x90)},
    {"RES 2, C", 0x91, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x91)},
    {"RES 2, D", 0x92, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x92)},
    {"RES 2, E", 0x93, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x93)},
    {"RES 2, H", 0x94, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x94)},
    {"RES 2, L", 0x95, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x95)},
    {"RES 2, (HL)", 0x96, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x96)},
    {"RES 2, A", 0x97, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x97)},
    {"RES 3, B", 0x98, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x98)},
    {"RES 3, C", 0x99, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x99)},
    {"RES 3, D", 0x9A, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x9A)},
    {"RES 3, E", 0x9B, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x9B)},
    {"RES 3, H", 0x9C, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x9C)},
    {"RES 3, L", 0x9D, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x9D)},
    {"RES 3, (HL)", 0x9E, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x9E)},
    {"RES 3, A", 0x9F, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0x9F)},

    {"RES 4, B", 0xA0, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xA0)},
    {"RES 4, C", 0xA1, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xA1)},
    {"RES 4, D", 0xA2, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xA2)},
    {"RES 4, E", 0xA3, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xA3)},
    {"RES 4, H", 0xA4, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xA4)},
    {"RES 4, L", 0xA5, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xA5)},
    {"RES 4, (HL)", 0xA6, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xA6)},
    {"RES 4, A", 0xA7, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xA7)},
    {"RES 5, B", 0xA8, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xA8)},
    {"RES 5, C", 0xA9, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xA9)},
    {"RES 5, D", 0xAA, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xAA)},
    {"RES 5, E", 0xAB, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xAB)},
    {"RES 5, H", 0xAC, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xAC)},
    {"RES 5, L", 0xAD, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xAD)},
    {"RES 5, (HL)", 0xAE, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xAE)},
    {"RES 5, A", 0xAF, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xAF)},

    {"RES 6, B", 0xB0, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xB0)},
    {"RES 6, C", 0xB1, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xB1)},
    {"RES 6, D", 0xB2, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xB2)},
    {"RES 6, E", 0xB3, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xB3)},
    {"RES 6, H", 0xB4, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xB4)},
    {"RES 6, L", 0xB5, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xB5)},
    {"RES 6, (HL)", 0xB6, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xB6)},
    {"RES 6, A", 0xB7, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xB7)},
    {"RES 7, B", 0xB8, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xB8)},
    {"RES 7, C", 0xB9, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xB9)},
    {"RES 7, D", 0xBA, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xBA)},
    {"RES 7, E", 0xBB, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xBB)},
    {"RES 7, H", 0xBC, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xBC)},
    {"RES 7, L", 0xBD, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xBD)},
    {"RES 7, (HL)", 0xBE, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xBE)},
    {"RES 7, A", 0xBF, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xBF)},

    {"SET 0, B", 0xC0, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xC0)},
    {"SET 0, C", 0xC1, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xC1)},
    {"SET 0, D", 0xC2, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xC2)},
    {"SET 0, E", 0xC3, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xC3)},
    {"SET 0, H", 0xC4, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xC4)},
    {"SET 0, L", 0xC5, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xC5)},
    {"SET 0, (HL)", 0xC6, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xC6)},
    {"SET 0, A", 0xC7, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xC7)},
    {"SET 1, B", 0xC8, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xC8)},
    {"SET 1, C", 0xC9, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xC9)},
    {"SET 1, D", 0xCA, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xCA)},
    {"SET 1, E", 0xCB, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xCB)},
    {"SET 1, H", 0xCC, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xCC)},
    {"SET 1, L", 0xCD, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xCD)},
    {"SET 1, (HL)", 0xCE, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xCE)},
    {"SET 1, A", 0xCF, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xCF)},

    {"SET 2, B", 0xD0, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xD0)},
    {"SET 2, C", 0xD1, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xD1)},
    {"SET 2, D", 0xD2, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xD2)},
    {"SET 2, E", 0xD3, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xD3)},
    {"SET 2, H", 0xD4, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xD4)},
    {"SET 2, L", 0xD5, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xD5)},
    {"SET 2, (HL)", 0xD6, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xD6)},
    {"SET 2, A", 0xD7, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xD7)},
    {"SET 3, B", 0xD8, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xD8)},
    {"SET 3, C", 0xD9, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xD9)},
    {"SET 3, D", 0xDA, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xDA)},
    {"SET 3, E", 0xDB, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xDB)},
    {"SET 3, H", 0xDC, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xDC)},
    {"SET 3, L", 0xDD, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xDD)},
    {"SET 3, (HL)", 0xDE, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xDE)},
    {"SET 3, A", 0xDF, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xDF)},

    {"SET 4, B", 0xE0, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xE0)},
    {"SET 4, C", 0xE1, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xE1)},
    {"SET 4, D", 0xE2, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xE2)},
    {"SET 4, E", 0xE3, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xE3)},
    {"SET 4, H", 0xE4, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xE4)},
    {"SET 4, L", 0xE5, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xE5)},
    {"SET 4, (HL)", 0xE6, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xE6)},
    {"SET 4, A", 0xE7, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xE7)},
    {"SET 5, B", 0xE8, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xE8)},
    {"SET 5, C", 0xE9, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xE9)},
    {"SET 5, D", 0xEA, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xEA)},
    {"SET 5, E", 0xEB, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xEB)},
    {"SET 5, H", 0xEC, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xEC)},
    {"SET 5, L", 0xED, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xED)},
    {"SET 5, (HL)", 0xEE, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xEE)},
    {"SET 5, A", 0xEF, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xEF)},

    {"SET 6, B", 0xF0, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xF0)},
    {"SET 6, C", 0xF1, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xF1)},
    {"SET 6, D", 0xF2, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xF2)},
    {"SET 6, E", 0xF3, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xF3)},
    {"SET 6, H", 0xF4, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xF4)},
    {"SET 6, L", 0xF5, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xF5)},
    {"SET 6, (HL)", 0xF6, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xF6)},
    {"SET 6, A", 0xF7, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xF7)},
    {"SET 7, B", 0xF8, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xF8)},
    {"SET 7, C", 0xF9, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xF9)},
    {"SET 7, D", 0xFA, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xFA)},
    {"SET 7, E", 0xFB, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xFB)},
    {"SET 7, H", 0xFC, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xFC)},
    {"SET 7, L", 0xFD, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xFD)},
    {"SET 7, (HL)", 0xFE, 2, 16, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xFE)},
    {"SET 7, A", 0xFF, 2, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::DisCB0xFF)},

    {{0}, 0, 0, 0, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &def}};
