#include "Opcodes.hpp"
#include "Disasm.hpp"

void def(CPU::Z80*) {
  return;
}

t_op opcodes[] = {
  {0x00, 4, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x00)},
  {0x01, 12, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x01)},
  {0x02, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x02)},
  {0x03, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x03)},
  {0x04, 4, {INST_SET, CLEAR, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x04)},
  {0x05, 4, {INST_SET, SET, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x05)},
  {0x06, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x06)},
  {0x07, 4, {CLEAR, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::Dis0x07)},
  {0x08, 20, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x08)},
  {0x09, 8, {UNCHANGED, CLEAR, INST_SET, INST_SET}, &(CPU::Disasm::Dis0x09)},
  {0x0A, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x0A)},
  {0x0B, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x0B)},
  {0x0C, 4, {INST_SET, CLEAR, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x0C)},
  {0x0D, 4, {INST_SET, SET, INST_SET, UNCHANGED}, &(CPU::Disasm::Dis0x0D)},
  {0x0E, 8, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &(CPU::Disasm::Dis0x0E)},
  {0x0F, 4, {CLEAR, CLEAR, CLEAR, INST_SET}, &(CPU::Disasm::Dis0x0F)},
  {0, 0, {UNCHANGED, UNCHANGED, UNCHANGED, UNCHANGED}, &def}
};
